DROP VIEW IF EXISTS dbs_registry.identifier_relationships;
DROP VIEW IF EXISTS dbs_registry.identifier_relationships_all_status;
DROP VIEW IF EXISTS dbs_registry.identifier_relationships_normalised;
DROP VIEW IF EXISTS dbs_registry.implicit_relationships;
DROP VIEW IF EXISTS dbs_registry.relationships;
DROP VIEW IF EXISTS dbs_registry.relationships_all_status;
DROP VIEW IF EXISTS dbs_registry.has_related_by_ds;

DROP TABLE IF EXISTS dbs_registry.spatial_extents;
DROP TABLE IF EXISTS dbs_registry.id_cache;
DROP TABLE IF EXISTS dbs_registry.id_cache_2;
DROP TABLE IF EXISTS dbs_registry.registry_object_relationships;
DROP TABLE IF EXISTS dbs_registry.registry_object_identifiers;
DROP TABLE IF EXISTS dbs_registry.registry_object_identifier_relationships;
DROP TABLE IF EXISTS dbs_registry.registry_object_identifier_relationships_normalised;
DROP TABLE IF EXISTS dbs_registry.registry_object_identifiers_normalised;
DROP TABLE IF EXISTS dbs_registry.search_statistics;
DROP TABLE IF EXISTS dbs_registry.vocab_metadata;
DROP TABLE IF EXISTS dbs_registry.institutional_pages;
DROP TABLE IF EXISTS dbs_registry.background_tasks;
DROP TABLE IF EXISTS dbs_registry.record_stats;
DROP TABLE IF EXISTS dbs_registry.registry_object_implicit_relationships;
DROP TABLE IF EXISTS dbs_registry.roles;

alter table dbs_registry.api_keys convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.api_requests convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.configs convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.data_source_attributes convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.data_source_logs convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.data_sources convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.dci convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.deleted_registry_objects convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.groups convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.harvest_requests convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.harvests convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.logs convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.orcid_exports convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.orcid_records convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.record_data convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_object_attributes convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_object_citations convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_object_links convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_object_metadata convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_object_tags convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_object_versions convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.registry_objects convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.schemas convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.scholix convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.sessions convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.tags convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.tasks convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.theme_pages convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.url_mappings convert to character set utf8mb4 collate utf8mb4_unicode_ci;
alter table dbs_registry.versions convert to character set utf8mb4 collate utf8mb4_unicode_ci;