<?php


namespace ANDS\Commands;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\Table;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ANDSCommand extends Command
{
    private $input;
    private $output;
    public $logs = [];

    /**
     * @return mixed
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * @return mixed
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * @return array
     */
    public function getLogs()
    {
        return $this->logs;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function setUp(InputInterface $input, OutputInterface $output)
    {
        $this->input = $input;
        $this->output = $output;
        initEloquent();
        date_default_timezone_set('UTC');
    }

    public function log($message, $wrapper = null)
    {
        $this->logs[] = ($wrapper ? "[{$wrapper}] " : "") . $message;

        if ($this->output) {
            if ($wrapper) {
                $this->output->writeln("<$wrapper>$message</$wrapper>");
                return;
            }
            $this->output->writeln($message);
        }

        return;
    }

    public function table($rows, $headers = [])
    {
        if (!$this->output) {
            print_r($rows);
            return;
        }
        $table = new Table($this->output);
        $table->setHeaders($headers)
            ->setRows($rows)
            ->render();
    }

    public function isQuite()
    {
        if ($this->output) {
            return $this->output->isQuite();
        }
        return true;
    }

    public function isVerbose()
    {
        if ($this->output) {
            return $this->output->isVerbose();
        }

        return true;
    }

    public function isDebug()
    {
        if ($this->output) {
            return $this->output->isDebug();
        }

        return true;
    }
}