<?php


namespace ANDS\Registry\Suggestors;


use ANDS\Repository\RegistryObjectsRepository;

class UserDataSuggestorTest extends \RegistryTestClass
{

    /** @test **/
    // this test has been disabled until work can be done ensure that the required elasticsearch data is available
    public function it_should_be_able_to_get_suggestion_for_a_given_record()
    {
        // TODO populate content before the fact
        $key = "AODN/0ad834fe-ea26-478a-a2d9-8bd8a47be842";
        $key = "Garbage:........AODN/0ad834fe-ea26-478a-a2d9-8bd8a47be842";
        $this->ensureKeyExist($key);
        $record = RegistryObjectsRepository::getPublishedByKey($key);

        $suggestor = new UserDataSuggestor();
        $suggestions = $suggestor->suggestByView($record);
        $this->assertNotEmpty($suggestions);
    }

    public function setUp()
    {
        // if ElasticSearch is not available, skip this test
        $suggestor = new UserDataSuggestor();
        if (!$suggestor->isClientOnline()) {
            $this->markTestSkipped("ElasticSearch is not available");
        }

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
