<?php

use ANDS\Cache\Cache;
use ANDS\Cache\CacheManager;
use ANDS\Registry\Providers\ORCID\ORCIDRecordsRepository;
use GraphAware\Neo4j\Client\ClientBuilder;

/**
 * Class Registry_object
 */
class Registry_object extends MX_Controller
{

    private $components = array();

    /**
     * Viewing a single registry object
     *
     * @return HTML generated by view
     * @internal param $_GET ['id'] $_GET['slug']  $_GET['any'] $_GET['key'``]parsed through the dispatcher
     */
    function view()
    {
        $this->load->library('blade');
        //Setup the variables
        $ro = null;
        $id = $this->input->get('id');
        $slug = $this->input->get('slug');
        $key = $this->input->get('key');
        $any = $this->input->get('any');
        $useCache = $this->input->get('useCache') == 'no' ? false : true;

        //If there's a single value to find, is id if numeric, otherwise it's slug
        if ($any) {
            if (is_numeric($any)) {
                $id = $any;
            } else {
                $slug = $any;
            }
        }

        //If an ID is provided
        //view/{id} => redirect to {slug}/{id}
        if ($id) {
            $ro = $this->ro->getByID($id, null, $useCache);
            if ($ro && $ro->prop['status'] == 'OK') {

                // CC-2103. found via id, redirect to {slug}/{id}
                if (!$slug || $slug != $ro->prop['core']['slug']) {
                    redirect($ro->prop['core']['slug'] . '/' . $id);
                }

            } elseif ($slug) {
                // view/{slug}/{id} where {id} not found, attempt to resolve slug
                $ro = $this->ro->getBySlug($slug, null, $useCache);
                if ($ro === "MULTIPLE") {
                    redirect('search/#!/slug=' . $slug);
                } elseif ($ro && $ro->prop['status'] == 'OK') {
                    //redirect to correct url
                    redirect($ro->prop['core']['slug'] . '/' . $ro->prop['core']['id']);
                }
            }
        }

        //dd($ro->prop['core']);
        if($ro && $ro->core['status'] == "DELETED")
        {

            $this->blade
                // ->set('scripts', array('view'))
                ->set('id', $this->input->get('id'))
                ->set('key', $this->input->get('key'))
                ->set('slug', $this->input->get('slug'))
                ->set('message', "")
                ->render('deleted_record');
            return;
        }

        //If a slug is provided
        //view/{slug} => redirect to {slug}/{id}
        //if there are multiple records => redirect to a search page
        if ((!$ro || $ro->prop['status'] == 'error') && $slug) {
            $ro = $this->ro->getBySlug($slug, null, $useCache);
            if ($ro === 'MULTIPLE') {
                redirect('search/#!/slug=' . $slug);
            } elseif ($ro && $ro->prop['status'] == 'OK') {
                redirect($slug . '/' . $ro->prop['core']['id']);
            }
        }

        //If a key is provided
        //view/?key={key} => redirect to {slug}/{id}
        if ((!$ro || $ro->prop['status'] == 'ERROR') && $key) {
            $record = \ANDS\Repository\RegistryObjectsRepository::getPublishedByKey($key);
            if ($record) {
                redirect($record->slug.'/'.$record->id);
            }
        }

        if ($ro && $ro->prop['status'] == 'OK') {
            //Found the record, handle rendering of normal view page
            if($ro->core['status'] == "DELETED")
            {
                $this->blade
                    // ->set('scripts', array('view'))
                    ->set('id', $this->input->get('id'))
                    ->set('key', $this->input->get('key'))
                    ->set('slug', $this->input->get('slug'))
                    ->set('message', "Record is Deleted")
                    ->render('deleted_record');
                return;
            }else{
                $this->displayRecord($ro);
            }


        } elseif (strpos($key, 'http://purl.org/au-research/grants/nhmrc/') !== false || strpos($key,
                'http://purl.org/au-research/grants/arc/') !== false
        ) {

            //[SPECIAL] Handle Soft 404 for grants

            //check if it's potentially an NHMRC key or ARC key
            if (strpos($key, 'http://purl.org/au-research/grants/nhmrc/') !== false) {
                $institution = 'National Health and Medical Research Council';
                $grantIdPos = strpos($key, 'nhmrc/') + 6;
            } else {
                $institution = 'Australian Research Council';
                $grantIdPos = strpos($key, 'arc/') + 4;
            }

            $grantId = substr($key, $grantIdPos);
            $purl = $key;

            // Set 404 HTTP Status code (CC-1633, CC-1712)
            $this->output->set_status_header('404');

            monolog([
                'event' => 'portal_view_notfound',
                'request' => [
                    'purl' => $purl,
                    'grant_id' => $grantId,
                    'institution' => $institution,
                    'type' => 'soft_404_activity'
                ]
            ], 'portal');

            $this->blade
                ->set('scripts', array('grant_form'))
                ->set('institution', $institution)
                ->set('grantId', $grantId)
                ->set('purl', $purl)
                ->render('soft_404_activity');
        } else {

            //No Record or Error
            $message = ($ro ? $ro->prop['status'] . NL . $ro->prop['message'] : false);

            // Set 404 HTTP Status code (CC-1633, CC-1712)
            $this->output->set_status_header('404');

            monolog([
                'event' => 'portal_view_notfound',
                'request' => [
                    'id' => $this->input->get('id'),
                    'key' => $this->input->get('key'),
                    'slug' => $this->input->get('slug'),
                    'any' => $this->input->get('any'),
                    'url' => current_url(),
                    'type' => 'soft_404'
                ]
            ], 'portal');

            $this->blade
                // ->set('scripts', array('view'))
                ->set('id', $this->input->get('id'))
                ->set('key', $this->input->get('key'))
                ->set('slug', $this->input->get('slug'))
                ->set('message', $message)
                ->render('soft_404');
        }
    }

    /**
     * Using blade to display the record
     * Construct the data that needs to be pre generated so that the render is seamless
     *
     * @param $ro
     */
    private function displayRecord($ro)
    {
        //Setup the common variables
        $banner = asset_url('images/collection_banner.jpg', 'core');
        $theme = ($this->input->get('theme') ? $this->input->get('theme') : '2-col-wrap');
        $logo = $this->getLogo($ro->core['group']);
        $group_slug = url_title($ro->core['group'], '-', true);

        //Depends on the class of the record, show different view
        switch ($ro->core['class']) {
            case 'collection':
                $render = 'registry_object/view';
                break;
            case 'activity':
                $render = 'registry_object/activity';
                $theme = ($this->input->get('theme') ? $this->input->get('theme') : 'activity');
                $banner = asset_url('images/activity_banner.jpg', 'core');
                break;
            case 'party':
                $render = 'registry_object/party';
                $theme = ($this->input->get('theme') ? $this->input->get('theme') : 'party');
                break;
            case 'service':
                $render = 'registry_object/service';
                $theme = ($this->input->get('theme') ? $this->input->get('theme') : 'service');
                break;
            default:
                $render = 'registry_object/view';
                break;
        }

        //Record a successful view only if the record is PUBLISHED

        if ($ro->core['status'] == 'PUBLISHED') {

            $ro->event('viewed');

            // record view event for logging
            $event = [
                'event' => 'portal_view',
                'record' => $this->getRecordFields($ro)
            ];

            // Record Source
            if ($this->input->get('source')) {
                $event['source'] = $this->input->get('source');
            }

            // Record Referal Query
            if ($this->input->get('refer_q')) {
                $event['refer_q'] = $this->input->get('refer_q');
            }

            monolog($event, 'portal', 'info');
        } else {
            //DRAFT Preview are not recorded, or should they?
        }


        // Determine resolved party identifiers
       $resolvedPartyIdentifiers = array();
        //to do - use mycelium to find these??
     //   if (isset($ro->relationships['researchers'])) {
     //       foreach ($ro->relationships['researchers']['docs'] as $rel) {
     //           if(is_array($rel)) {
     //               $rels = is_array($rel['relation_origin']) ? $rel['relation_origin'] : array($rel['relation_origin']);
     //               if ((in_array('IDENTIFIER', $rels) || in_array('IDENTIFIER REVERSE', $rels)) && $rel['from_id'] != '' && array_key_exists('relation_identifier_identifier', $rel)) {
     //                   $resolvedPartyIdentifiers[] = $rel['relation_identifier_identifier'];
     //               }
     //           }
     //       }
     //   }

        // Theme Page

        if (isset($ro->core['theme_page'])) {
            $the_theme = array();
            foreach($ro->core['theme_page'] as $a_theme) {
                $the_theme[] = $this->getTheme($a_theme);
            }
        }else{
            $the_theme = false;
        }

        //Decide whethere to show the duplicate identifier
        $show_dup_identifier_qtip = true;
        if ($this->input->get('fl') !== false) {
            $show_dup_identifier_qtip = false;
        }
        $fl = '?fl';

        //construct displayable relationship array with business logic built in
        $related = $this->getRelationship($ro);

        $related['total'] = [
            'count' => collect($related)->pluck('count')->sum()
        ];

        //Do the rendering
        $this->blade
            ->set('scripts', array('view', 'view_app', 'tag_controller'))
            ->set('lib', array('jquery-ui', 'dynatree', 'qtip', 'map'))
            ->set('relatedLimit', 5)
            ->set('ro', $ro)
            ->set('resolvedPartyIdentifiers', $resolvedPartyIdentifiers)
            ->set('contents', $this->components['view'])
            ->set('aside', $this->components['aside'])
            ->set('view_headers', $this->components['view_headers'])
            ->set('url', $ro->construct_api_url())
            ->set('theme', $theme)
            ->set('theme_page', $the_theme)
            ->set('logo', $logo)
            ->set('isPublished', $ro->core['status'] == 'PUBLISHED')
            ->set('banner', $banner)
            ->set('group_slug', $group_slug)
            ->set('fl', $fl)
            ->set('show_dup_identifier_qtip', $show_dup_identifier_qtip)
            ->set('related', $related)
            ->set('debugOn', $this->input->get('debug') == 'on' ? true : false)
            ->render($render);
    }

    /**
     * @todo update internal mapping to call ro model directly
     * @param _ro $ro
     * @return array
     */
    private function getRecordFields(_ro $ro)
    {
        return $this->ro->getRecordFields($ro);
    }

    /**
     * Export Controller
     * @param  string $type endnote|endnote_web
     * @param  string $ids "-" separated list of ids. eg 5435-23443
     * @return redirect
     */
    public function export($type = 'endnote', $ids)
    {
        // capture the event
        $ids = explode('-', $ids);
        $event = [
            'event' => 'portal_export',
            'record_ids' => $ids,
            'export_type' => $type,
        ];

        // determine single record
        if (count($ids) == 1 &&
            $ro = $this->ro->getByID($ids[0], ['core'], false)
        ) {
            $event['record'] = $this->getRecordFields($ro);
        }

        //determine source
        if ($source = $this->input->get('source')) {
            $event['source'] = $source;
        }

        monolog($event, 'portal', 'info');

        /**
         * forward them to
         * registry/registry_object@exportToEndNote/{:ids}.ris?foo=timestamp
         * @todo make export a portal only functionality
         * @todo investigate in making an export registry API instead
         */
        $exportUrl = registry_url('registry_object/exportToEndNote/' . implode('-', $ids) . '.ris?foo=' . time());

        // Redirection switchboard
        switch ($type) {
            case "endnote":
                redirect($exportUrl);
                break;
            case "endnote_web":
                $endNoteWebUrl = "http://www.myendnoteweb.com/?func=directExport&partnerName=ResearchDataAustralia&dataIdentifier=1&dataRequestUrl=" . $exportUrl;
                redirect($endNoteWebUrl);
                break;
        }
    }

    /**
     * Returns the relationship array primed for display
     *
     * @param $ro
     * @return array
     */
    private function getRelationship($ro)
    {
        //initialisation to prevent logic error
        $related = $ro->relationships;
        //var_dump($ro->relationships);
      //  return $related;
        if (!$related) $related = [];

     /*   foreach ($related as &$rel) {
            foreach ($rel['docs'] as &$doc) {
                $doc['display_relationship'] = [];
                if (array_key_exists('relation', $doc)) {
                    foreach ($doc['relation'] as $index => $docRelation) {
                        $origin = 'EXPLICIT';
                        if (isset($doc['relation_origin'][$index])) {
                            $origin = $doc['relation_origin'][$index];
                        }
                        $doc['display_relationship'][] = readable($docRelation, $origin, $doc['from_class'], $doc['to_class']);
                    }
                }
                $doc['display_relationship'] = array_unique($doc['display_relationship']);
                $doc['display_relationship'] = implode(', ', $doc['display_relationship']);
                $doc['display_description'] = '';
            }

        } */

        // search class for constructing search queries
        $searchClass = $ro->core['class'];
        if ($ro->core['class'] == 'party') {
            if (strtolower($ro->core['type']) == 'group') {
                $searchClass = 'party_multi';
            } else {
                $searchClass = 'party_one';
            }
        }

        // construct the correct search query for each type of related
        $relatedArray = ['data', 'software','programs', 'grants_projects', 'services', 'organisations', 'researchers'];
        foreach ($relatedArray as $rr) {
            $query = [];
            switch ($rr) {
                case "data":
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'collection', 'collection_type' => '-type:software','sort' => 'score desc'];
                    break;
                case "software":
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'collection', 'type' => 'software', 'sort' => 'score desc'];
                    break;
                case "programs":
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'activity', 'type' => 'program', 'sort' => 'score desc'];
                    break;
                case "grants_projects":
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'activity', 'nottype' => 'program', 'sort' => 'score desc'];
                    break;
                case "services":
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'service', 'sort' => 'score desc'];
                    break;
                case "organisations";
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'party', 'type' => 'group', 'sort' => 'score desc'];
                    break;
                case "researchers":
                    $query = ['related_' . $searchClass . '_id' => $ro->id, 'class' => 'party', 'nottype' => 'group', 'sort' => 'score desc'];
                    break;
            }
            $related[$rr]['searchUrl'] = constructPortalSearchQuery($query);

            // fix count in case not all records are synced correctly
       /*     if (array_key_exists('count', $related[$rr]) && $related[$rr]['count'] > 5) {
                $related[$rr]['count'] = $this->getSolrCountForQuery($query);
            } elseif (!array_key_exists('count', $related[$rr])) {
                $related[$rr]['count'] = 0;
            }

            if (!array_key_exists('docs', $related[$rr])) {
                $related[$rr]['docs'] = [];
            }

            if ($rr == "researchers" || $rr == "organisations") {
                $related[$rr]['docs'] = $this->researcherSort($related[$rr]['docs']);
            } */
        }

        // Fix duplicate researchers display value TODO: investigate why
       // $related['researchers']['contents'] = collect($related['researchers']['contents'])
         //   ->unique()->toArray();

        return $related;
    }

    /**
     * Preview popup HTML content
     * Used when the user click on a related object link
     *
     * @author Minh Duc Nguyen <minh.nguyen@ands.org.au>
     * @return view
     */
    function preview()
    {
        $this->load->library('blade');

        if ($this->input->get('ro_id')) {
            $ro = $this->ro->getByID($this->input->get('ro_id'));
            $omit = $this->input->get('omit') ? $this->input->get('omit') : false;

            monolog(
                array(
                    'event' => 'portal_preview',
                    'record' => $this->getRecordFields($ro)
                ),
                'portal', 'info'
            );

            $this->blade
                ->set('ro', $ro)
                ->set('related', $this->getRelationship($ro))
                ->set('source', $this->input->get('source'))
                ->set('omit', $omit)
                ->render('registry_object/preview');
        } elseif ($this->input->get('identifier_relation_id')) {

            $input = $this->input->get('identifier_relation_id');
            $input = urldecode($input);
            $input_array = json_decode($input);
            $input_array->connections_preview_div="";
            $identifiers_div = "";
            $identifier_count = 0;
            $connections_preview_div = "";
            foreach ($input_array->relations as $i) {
                // todo - implement resolvable links for the identifier if possible
               $identifiers_div .= $i->to_identifier;
               $identifier_count++;
            }
            $identifiers_div = "<h5>Identifier" . ($identifier_count > 1 ? 's' : '') . ": </h5>" . $identifiers_div;

          //  if ($related_info->notes) {
          //      $connections_preview_div .= '<p>Notes: ' . (string)$related_info->notes . '</p>';
         //   }
            $imgUrl = asset_url('img/' . $input_array->to_type . '.png', 'base');
            $classImg = '<img class="icon-heading" src="' . $imgUrl . '" alt="' . $input_array->to_type . '" style="width:24px; float:right;">';
            $connections_preview_div = '<div class="previewItemHeader">' . $input_array->relations[0]->relation_type_text . '</div>' . $classImg . '<h4>' . $input_array->to_title . '</h4><div class="post">' . $identifiers_div . "<br/>" . $connections_preview_div . '</div>';
            $input_array->connections_preview_div = $connections_preview_div;

            $fr= $input_array;
           // if ($result->num_rows() > 0) {
          //      $fr = $result->first_row();

          //      $ro = $this->ro->getByID($fr->registry_object_id);
             //   monolog(
            //        array(
            //            'event' => 'portal_preview_identifier',
            //            'record' => $this->getRecordFields($ro),
             //           'identifier_relation_id' => $this->input->get('identifier_relation_id')
             //       ),
             //       'portal', 'info'
             //   );


                $ro = false;

                $pullback = false;

                //ORCID "Pull back"
                if ($fr->to_type == 'party' && $fr->to_identifier_type == 'orcid' && isset($fr->to_identifier)) {

                   $orcid = ORCIDRecordsRepository::obtain($fr->to_identifier);
                   if($orcid != null){
                        $bio = json_decode($orcid->record_data, true);
                        $pullback = [
                            'name' => $orcid->full_name,
                            'bio' => $bio,
                            'bio_content' => $bio['person']['biography']['content'],
                            'orcidRecord' => $orcid,
                            'orcid' => $orcid->orcid_id
                        ];
                   }
                    $filters = array('identifier_value' => $fr->to_identifier);
                    $ro = $this->ro->findRecord($filters);
                }
                $this->blade
                    ->set('record', $input_array )
                    ->set('ro', $ro)
                    ->set('pullback', $pullback)
                    ->render('registry_object/preview-identifier-relation');

        } else {
            if ($this->input->get('identifier_doi')) {
                $identifier = $this->input->get('identifier_doi');

                //DOI "Pullback"
                $pullback = $this->ro->resolveIdentifier('doi', $identifier);
                $ro = $this->ro->findRecord(array('identifier_value' => $identifier));

                monolog(
                    array(
                        'event' => 'portal_preview_doi',
                        'record' => $ro ? $this->getRecordFields($ro) : null,
                        'identifier_doi' => $this->input->get('identifier_doi')
                    ),
                    'portal', 'info'
                );

                $this->blade
                    ->set('ro', $ro)
                    ->set('pullback', $pullback)
                    ->render('registry_object/preview_doi');
            }
        }
    }

    /**
     * Returns sorted related researchers
     *
     * @param array unsorted related researchers
     */

    function researcherSort($related){
        //extract out the principal investigators into new array and remove them from the researcher's array
        $principals = array();
        $chiefs = array();

        foreach($related as $key=>$relation){
            if(isset($relation['relation'])){
                foreach($relation['relation']as $relationship) {
                    if(strpos($relationship,"rincipal")!==false){
                        array_push($principals, $relation);
                        unset($related[$key]);
                    }
                    if(strpos($relationship,"hief")!==false){
                        array_push($chiefs, $relation);
                        unset($related[$key]);
                    }
                } 
            }
        }

        //sort both arrays on name of surname (most likely the last word) from the title of related party
        uasort($principals, function ($a, $b) {
            return strnatcmp(last(explode(' ', $a["to_title"])), last(explode(' ', $b["to_title"])));
        });
        uasort($chiefs, function ($a, $b) {
            return strnatcmp(last(explode(' ', $a["to_title"])), last(explode(' ', $b["to_title"])));
        });

        uasort($related, function ($a, $b) {
            return strnatcmp(last(explode(' ', $a["to_title"])), last(explode(' ', $b["to_title"])));
        });

        //now join both arrays back together
        $related = array_merge($principals, $chiefs , $related);

        return $related;
    }

    /**
     * Returns the vocabulary element
     * todo move to the vocab component
     *
     * @param string $vocab
     */
    function vocab($vocab = 'anzsrc-for')
    {
        $uri = $this->input->get('uri');
        $data = json_decode(file_get_contents("php://input"), true);
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');
        $filters = $data['filters'];
        $this->load->library('vocab');
        if (!$uri) { //get top level

            if ($vocab == 'anzsrc-for' || $vocab == 'anzsrc-seo'|| $vocab == 'anzsrc-for-2020' || $vocab == 'anzsrc-seo-2020') {
                $toplevel = $this->vocab->getTopLevel($vocab, $filters);
                echo json_encode($toplevel['topConcepts']);
            } else {
                $toplevel = $this->getSubjectsVocab($vocab, $filters);
                echo json_encode($toplevel);
            }

        } else {
            $r = array();
            $result = json_decode($this->vocab->getConceptDetail($vocab, $uri), true);
            if (isset($result['result']['primaryTopic']['narrower'])) {
                foreach ($result['result']['primaryTopic']['narrower'] as $narrower) {
                    $curi = $narrower['_about'];
                    $concept = json_decode($this->vocab->getConceptDetail($vocab, $curi), true);
                    $concept = array(
                        'notation' => $concept['result']['primaryTopic']['notation'],
                        'prefLabel' => $concept['result']['primaryTopic']['prefLabel']['_value'],
                        'uri' => $curi,
                        'collectionNum' => $this->vocab->getNumCollections($curi, $filters),
                        'has_narrower' => (isset($concept['result']['primaryTopic']['narrower']) && sizeof($concept['result']['primaryTopic']['narrower']) > 0) ? true : false
                    );

                    array_push($r, $concept);
                }
            }
            echo json_encode($r);
        }
    }

    /**
     * Returns the subject list for vocab
     * Used for Advanced Search
     * todo move to the vocab component
     *
     * @param $vocab_type
     * @param $filters
     * @return array
     */
    function getSubjectsVocab($vocab_type, $filters)
    {
        $result = array();
        $result_type = $this->getAllSubjectsForType($vocab_type, $filters);
        if (isset($result_type['list'])) {
            $result = array_merge($result, $result_type['list']);
        }

        $azTree = array();
        $azTree['0-9'] = array('subtree' => array(), 'collectionNum' => 0, 'prefLabel' => '0-9', 'notation' => '0-9');
        foreach (range('A', 'Z') as $i) {
            $azTree[$i] = array(
                'subtree' => array(),
                'collectionNum' => 0,
                'prefLabel' => $i,
                'notation' => url_title($i)
            );
        }

        foreach ($result as $r) {
            if (strlen($r['prefLabel']) > 0) {
                $first = strtoupper($r['prefLabel'][0]);
                if (is_numeric($first)) {
                    $first = '0-9';
                }
                if (ctype_alnum($first) && isset($azTree[$first])) {
                    $azTree[$first]['collectionNum']++;
                    array_push($azTree[$first]['subtree'], $r);
                }
            }
        }

        foreach ($azTree as &$com) {
            $com['has_narrower'] = $com['collectionNum'] > 0 ? true : false;
        }

        $result = array();
        foreach ($azTree as $com) {
            array_push($result, $com);
        }
        return $result;
    }

    /**
     * Returns all subjects for a particular subject type
     * Used by getSubjectsVocab
     * todo move to vocab component
     *
     * @param $type
     * @param $filters
     * @return array|bool
     */
    private function getAllSubjectsForType($type, $filters)
    {
        $this->load->library('solr');
        $this->solr
            ->setOpt('q', '*:*')
            ->setOpt('defType', 'edismax')
            ->setOpt('mm', '3')
            ->setOpt('q.alt', '*:*')
            ->setOpt('fl', '*, score')
            ->setOpt('qf', 'id^1 group^0.8 display_title^0.5 list_title^0.5 fulltext^0.2')
            ->setOpt('rows', '0')
            ->clearOpt('fq');

        if ($filters) {
            $this->solr->setFilters($filters);
        } else {
            $this->solr->setBrowsingFilter();
        }

        $this->solr
            ->setOpt('fq', '+tsubject_' . $type . ':*')
            ->setFacetOpt('field', 'tsubject_' . $type)
            ->setFacetOpt('limit', '25000');

        $content = $this->solr->executeSearch(true);

        //if still no result is found, do a fuzzy search, store the old search term and search again
        if ($this->solr->getNumFound() == 0) {
            if (!isset($filters['q'])) {
                $filters['q'] = '';
            }
            $new_search_term_array = explode(' ', $filters['q']);
            $new_search_term = '';
            foreach ($new_search_term_array as $c) {
                $new_search_term .= $c . '~0.7 ';
            }
            // $new_search_term = $data['search_term'].'~0.7';
            $this->solr->setOpt('q',
                'fulltext:(' . $new_search_term . ') OR simplified_title:(' . iconv('UTF-8', 'ASCII//TRANSLIT',
                    $new_search_term) . ')');
            $content = $this->solr->executeSearch(true);
        }

        if (isset($content['facet_counts']) && isset($content['facet_counts']['facet_fields'])) {
            $facets = $content['facet_counts']['facet_fields'];
        } else {
            return false;
        }

        $result = [
            'list' => []
        ];

        foreach ($facets as $facet) {
            for ($i = 0; $i < sizeof($facet) - 1; $i += 2) {
                $name = $facet[$i];
                $count = $facet[$i + 1];
                $result['list'][] = [
                    'prefLabel' => $name,
                    'collectionNum' => $count,
                    'notation' => $name
                ];
            }
        }

        return $result;
    }

    /**
     * Returns a list of subjects with their slug
     * todo find out where this is needed
     * todo move to vocab component if it is needed, refactor required
     */
    public function getSubjects()
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');
        $result = array();
        foreach ($this->config->item('subjects') as $subject) {
            $slug = url_title($subject['display'], '-', true);
            foreach ($subject['codes'] as $code) {
                $result[$slug][] = 'http://purl.org/au-research/vocabulary/anzsrc-for/2008/' . $code;
            }
        }
        echo json_encode($result);
    }

    /**
     * Resolves subjects
     * todo find out if this is needed
     * todo move to vocab component if needed, refactor
     *
     * @param $vocab
     */
    function resolveSubjects($vocab)
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');
        $data = json_decode(file_get_contents("php://input"), true);
        $subjects = $data['data'];

        $this->load->library('vocab');

        $result = array();

        if (is_array($subjects)) {
            foreach ($subjects as $subject) {
                $r = json_decode($this->vocab->getConceptDetailBySubject($vocab, $subject), true);
                $result[$subject] = $r['result']['primaryTopic']['prefLabel']['_value'];
            }
        } else {
            $r = $r = json_decode($this->vocab->getConceptDetailBySubject($vocab, $subjects), true);
            $result[$subjects] = $r['result']['primaryTopic']['prefLabel']['_value'];
        }


        echo json_encode($result);
    }

    /**
     * Adding a tag to a record API end point
     * todo move to the api/registry/object/:id/tag REST API endpoint instead
     * todo update AJAX call
     */
    function addTag()
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');
        $data = json_decode(file_get_contents("php://input"), true);

        $data = $data['data'];
        $data['user'] = $this->user->name();
        $data['user_from'] = $this->user->authDomain() ? $this->user->authDomain() : $this->user->authMethod();

        $fields = '';
        foreach ($data as $key => $value) {
            $fields .= $key . '=' . rawurlencode($value) . '&';
        }//build the string

        $content = curl_post(base_url() . 'registry/services/rda/addTag', $fields,
            array('header' => 'multipart/form-data'));
        $this->_dropCache($data['id']);

        monolog([
            'event' => 'portal_tag_add',
            'tag' => ['value' => $data['tag'] ],
            'record' => ['key' => $data['key'] ]
        ], 'portal', 'info');

        echo $content;
    }

    /**
     * Returns the stat of a record
     * todo move to the api/registry/object/:id/stat REST API endpoint instead
     * todo update AJAX call
     *
     * @param  int $id
     * @return json
     */
    function stat($id)
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');
        $this->load->model('registry_objects', 'ro');
        $ro = $this->ro->getByID($id);
        $stats = $ro->stat();

        echo json_encode($stats);
    }

    /**
     * increment the stats for a specified type by the value given
     * Returns the stat of a record
     * todo move to the api/registry/object/:id/stat REST API endpoint instead
     * todo update AJAX call
     *
     * @param  int $id
     * @return json
     */
    function add_stat($id)
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');
        $data = json_decode(file_get_contents("php://input"), true);
        $type = $data['data']['type'];
        $value = intval($data['data']['value']);
        $this->load->model('registry_objects', 'ro');
        $ro = $this->ro->getByID($id);

        $ro->event($type, $value);

        $event = [
            'event' => 'portal_'.$type
        ];

        $event['record'] = $this->getRecordFields($ro);
        if (isset($data['data']['url'])) {
            $event['accessed_url'] = $data['data']['url'];
        }

        monolog($event, 'portal', 'info');

        $stats = $ro->stat();

        echo json_encode($stats);
    }

    /**
     * Search View
     * Displaying the search view for the current component
     *
     * @return HTML
     */
    function search()
    {
        //redirect to the correct URL if q is used in the search query
        if ($this->input->get('q')) {
            redirect('search/#!/q=' . $this->input->get('q'));
        }

        // Prevent indexing of this page by search engines
        $this->output->set_header('X-Robots-Tag: noindex, nofollow');

        $this->load->library('blade');
        $this->blade
            ->set('lib', array('ui-events', 'angular-ui-map', 'google-map'))
            // ->set('scripts', array('search_app'))
            // ->set('facets', $this->components['facet'])
            ->set('search', true)//to disable the global search
            ->render('registry_object/search');
    }

    /**
     * Search View for collections of type software
     * Displaying the search view for software type records
     *
     * @return HTML
     */
    function software()
    {
        //redirect to the correct URL to add software type to the search query
        redirect('search/#!/q=/collection_type=type%3Asoftware/');

        // Prevent indexing of this page by search engines
        $this->output->set_header('X-Robots-Tag: noindex, nofollow');

        $this->load->library('blade');
        $this->blade
            ->set('lib', array('ui-events', 'angular-ui-map', 'google-map'))
            ->set('search', true)//to disable the global search
            ->render('registry_object/search');
    }


    /**
     * Search View for Subjects Browser
     * Displaying the search view for the current component
     *
     * @return HTML
     */
    function subjects()
    {
        //redirect to the correct URL if q is used in the search query
        if ($this->input->get('q')) {
            redirect('subjects/#!/q=' . $this->input->get('q'));
        }

        $this->load->library('blade');
        $this->blade
            ->set('lib', array('ui-events', 'angular-ui-map'))
            // ->set('scripts', array('search_app'))
            // ->set('facets', $this->components['facet'])
            ->set('search', true)//to disable the global search
            ->render('registry_object/subjects');
    }

    /**
     * Do a quick SOLR search and get the count for said queries
     * @param $queries
     */
    public function getSolrCountForQuery($filters){

        // CC-2141. only the get count, doesn't care about any of the data
        // rows to 0 just in case, to prevent large document cause memory overflow
        $filters = array_merge($filters, ['fl' => 'id', 'rows' => 0]);

        $this->load->library('solr');
        $result = $this->solr->init()->setFilters($filters)->executeSearch(true);

        return $result['response']['numFound'];
    }

    /**
     * Main search function
     * SOLR search
     *
     * @param bool $no_log
     * @return json
     */
    function filter($no_log = false)
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');

        $data = json_decode(file_get_contents("php://input"), true);
        $filters = isset($data['filters']) ? $data['filters'] : false;

        // experiment with delayed response time
        // sleep(2);

        $this->load->library('solr');

        //restrict to default class
        $default_class = isset($filters['class']) ? $filters['class'] : 'collection';
        if (!is_array($default_class)) {
            $this->solr->setOpt('fq', '+class:' . $default_class);
        }

        $this->solr->setFilters($filters);


        //flags, these are the only fields that will be returned in the search
        $flags = [
            'id',
            'type',
            'title',
            'description',
            'group',
            'data_source_id',
            'slug',
            'spatial_coverage_centres',
            'spatial_coverage_polygons',
            'administering_institution',
            'researchers',
            'matching_identifier_count',
            'list_description',
            'earliest_year',
            'latest_year'
        ];
        $this->solr->setOpt('fl', implode(',', $flags));

        //highlighting
        $this->solr
            ->setOpt('hl', 'true')
            ->setOpt('hl.fl',
                'identifier_value_search, related_party_one_search, related_party_multi_search, related_activity_search, related_service_search, group_search, related_info_search, subject_value_resolved_search, description_value, citation_info_search')
            ->setOpt('hl.simple.pre', '&lt;b&gt;')
            ->setOpt('hl.simple.post', '&lt;/b&gt;')
            ->setOpt('hl.snippets', '2');

        //extract sentence
        $this->solr
            ->setOpt('hl.fragmenter', 'regex')
            ->setOpt('hl.fragsize', '140')
            ->setOpt('hl.regex.slop', '1.0')
            ->setOpt('hl.regex.pattern', "\w[^.!?]{400,600}[.!?]")
            ->setOpt('hl.bs.type', "SENTENCE")
            ->setOpt('hl.bs.maxScan', "30");

        // facets configuration
        $this->solr
            ->setFacetOpt('mincount', '1')
            ->setFacetOpt('limit', '100')
            ->setFacetOpt('sort', 'count');

        //temporal facet
        $this->solr
            ->setFacetOpt('field', 'earliest_year')
            ->setFacetOpt('field', 'latest_year')
            ->setOpt('f.earliest_year.facet.sort', 'count asc')
            ->setOpt('f.latest_year.facet.sort', 'count');

        $this->solr
            ->setFacetOpt('query', '-type:software')
            ->setFacetOpt('query', 'type:software');

        /**
         * Set facets based on class
         * todo clean this up
         */
        if ($default_class == 'activity') {
            foreach ($this->components['activity_facet'] as $facet) {
                if ($facet != 'temporal' && $facet != 'spatial') {
                    $this->solr->setFacetOpt('field', $facet);
                }
            }
        } elseif ($default_class == 'collection') {
            foreach ($this->components['facet'] as $facet) {
                if ($facet != 'temporal' && $facet != 'spatial' && $facet != 'collection_type') {
                    $this->solr->setFacetOpt('field', $facet);
                }
                if($facet == 'collection_type'){
                    $this->solr->setFacetOpt('query',$facet);
                }
            }
        } else {
            foreach ($this->components['facet'] as $facet) {
                if ($facet != 'temporal' && $facet != 'spatial') {
                    $this->solr->setFacetOpt('field', $facet);
                }
            }
        }

        // Finally execute the search and get the result
        $result = $this->solr->executeSearch(true);

        //fuzzy search only if there's no result found
        if ($this->solr->getNumFound() == 0 && isset($filters['q'])) {
            $new_search_term_array = explode(' ', escapeSolrValue($filters['q']));
            $new_search_term = '';
            foreach ($new_search_term_array as $c) {
                $new_search_term .= $c . '~0.7 ';
            }
            // $new_search_term = $data['search_term'].'~0.7';
            $this->solr->setOpt('q',
                '_text_:(' . $new_search_term . ') OR simplified_title:(' . iconv('UTF-8', 'ASCII//TRANSLIT',
                    $new_search_term) . ')');
            $result = $this->solr->executeSearch(true);
            if ($this->solr->getNumFound() > 0) {
                $result['fuzzy_result'] = true;
            }
        }

        //not recording a hit for the quick search done for advanced search
        /** @var boolean $no_log */
        if (!$no_log && array_key_exists('response', $result)) {

            $event = array(
                'event' => 'portal_search'
            );

            $event['filters'] = $filters ? $filters : [];

            //record search result set
            $result_id = array();
            $result_group = array();
            $result_dsid = array();
            foreach ($result['response']['docs'] as $doc) {
                $result_id[] = $doc['id'];
                $result_group[] = $doc['group'];
                $result_dsid[] = $doc['data_source_id'];
            }
            $result_group = array_values(array_unique($result_group));
            $result_dsid = array_values(array_unique($result_dsid));

            // record the search result additional
            $event['result'] = [
                'numFound' => $result['response']['numFound'],
                'result_id' => $result_id,
                'result_group' => $result_group,
                'result_dsid' => $result_dsid
            ];

            monolog($event, 'portal', 'info');
        }

        // sanity check on the Query String we use SOLR to search
        $result['url'] = $this->solr->constructFieldString();

        echo json_encode($result);
    }

    /**
     * List all attribute of a registry object
     * todo find out if this is necessary, act accordingly
     *
     * @param        $id
     * @param string $params
     * @return json
     */
    function get($id, $params = '')
    {
        header('Cache-Control: no-cache, must-revalidate');
        header('Content-type: application/json');
        set_exception_handler('json_exception_handler');

        $params = explode('-', $params);
        if (empty($params)) {
            $params = array('core');
        }

        $this->load->model('registry_objects', 'ro');
        $ro = $this->ro->getByID($id, $params);
        echo json_encode($ro->prop);
    }

    /**
     * Get the logo url for a groups logo if it exists!
     * todo refactor to use registry api instead
     *
     * @param $group
     * @return string
     */
    function getLogo($group)
    {
        $this->load->model('group/groups', 'group');
        $logo = $this->group->fetchLogo($group);
        return $logo;
    }

    /**
     * Get the theme page of the record
     *
     * @param $slug
     * @return string
     */
    function getTheme($slug)
    {
        $url = registry_url() . 'services/rda/getThemePageIndex';
        $all_themes = json_decode(@file_get_contents($url), true);
        $the_theme = array();
        foreach ($all_themes['items'] as $theme) {

            if ($theme['slug'] == $slug) {
                $the_theme['title'] = $theme['title'];
                $the_theme['img_src'] = $theme['img_src'];
                return $the_theme;
            }
        }
        return false;
        // print_r($contents);
    }

    /**
     * Construction
     * Defines the components that will be displayed and search for within the application
     */
    function __construct()
    {
        parent::__construct();
        $this->load->model('registry_objects', 'ro');
        $this->components = array(
            'view' => array(
                'descriptions',
                'reuse-list',
                'quality-list',
                'dates-list',
                'connectiontree',
                'related-objects-list',
                'spatial-info',
                'subjects-list',
                'related-metadata',
                'identifiers-list'
            ),
            'aside' => array('rights-info', 'contact-info'),
            'view_headers' => array('title', 'related-parties'),
            'facet' => array('spatial', 'group', 'license_class', 'access_methods_ss','type', 'temporal', 'access_rights'),
            'activity_facet' => array(
                'type',
                'activity_status',
                'funding_scheme',
                'administering_institution',
                'funders'
            )
        );
    }

    /**
     * Dropping the cache of this registry object ID
     * todo determine the nessessity of this function
     *
     * @param $ro_id
     */
    function _dropCache($ro_id)
    {
        $api_id = 'ro-api-' . $ro_id . '-portal';
        $portal_id = 'ro-portal-' . $ro_id;
        $ci =& get_instance();
        $ci->load->driver('cache');
        try {
            $ci->cache->file->delete($api_id);
            $ci->cache->file->delete($portal_id);
        } catch (Exception $e) {

        }
    }
}
